---
- name: Pull docker image of
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull darshan4163264/calculatorproj

    - name: running container
      shell: docker create -it --name calc darshan4163264/calculatorproj
