---
- name: Pull docker image of
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull duston04/calculatorproj

    - name: running container
      shell: docker run -it -d duston04/calculatorproj